### ISSUE TITLE
[suggestion] Grab title and author(s) from head, and set metadata

### ISSUE THREAD

**Issue by Shohreh** [hafaio/repub#11]
Hello,

_(It's not a bug, but since that page has no Discussion section to post suggestions…)_

rePub is a great tool to read long articles from the web on my e-reader.

To see those useful infos on the reader, if available, I suggest grabing the title + author(s) from the HTML header, and use those as metadata in the EPUB file.

```
<head>
<title>Some title</title>
<meta name="author" content="John Doe">
```

Currently, I copy those infos from the web page manually, use them to change the filename (Some author#some title.epub), and run a Python script to edit the EPUB file accordingly.

Cheers,

**Comment by erikbrinkman** [comment]
This is a great place for feature requests too, and in general what youre asking doesn't seem too difficult, but I do have a few questions if you'll indulge me.

Most e-readers pull from the metadata attached to the epub itself, rather than head of the contents itself. This metadata is updated appropriately, and this is what mac books picks up, for example:

<img width="209" alt="Screenshot 2024-11-24 at 11 43 43" src="https://github.com/user-attachments/assets/f441d408-18c8-44a9-878c-aeac044d9754">

However, it seems like your reader is not picking those up? As a work around, you wrote a simple python script to edit them back into the file in a way that works? Can you share your script so I know what you're editing? It seems like I am setting the title inside `OEBPS/section_0.xhtml` which is the main context, but not setting the author in the head. Would just adding `<meta name="author" content="...">` to the head of the content section be sufficient for your reader to pick it up?

Or the issue that I'm not actually extracting this information correctly from the websites that you're clipping. If that's the case, I can also try and update that logic accordingly if you give me an example website that's not being parsed correctly.

I know I'm asking for a lot of info, but hopefully this enables me to help you out!

**Comment by Shohreh** [comment]
It's just that some websites use generic data for the title and/or author(s), which doesn't help knowing what a file is when listed in my e-reader. But they might contain the right data in the HTML header, hence my suggestion.

This is the Python scriptlet I wrote to edit the file's metadata from the filename:
```
#pip3 install ebookmeta
import ebookmeta
import pyperclip
import os, sys

#======== grab input filename from clipboard
INPUTFILE = pyperclip.paste()
if not INPUTFILE or ".epub" not in INPUTFILE:
	print ("Must pass an EPUB filename")
	exit()

print(f"Handling {INPUTFILE}")

#======== grab author + title from filename: author#title.epub
x = [x.strip() for x in INPUTFILE.split('#')]
file_author=x[0]
#ignore file extension
file_title, _ = os.path.splitext(x[1])

#======== edit metadata: set author + title
meta = ebookmeta.get_metadata(INPUTFILE)
meta.set_author_list_from_string(file_author)
meta.title = file_title
print(f"Title:{meta.title}, Author:{meta.author_list[0]}")
ebookmeta.set_metadata(INPUTFILE, meta)
```

**Comment by Shohreh** [comment]
It's just that some websites use generic data for the title and/or author(s), which doesn't help knowing what a file is when listed in my e-reader. But they might contain the right data in the HTML header, hence my suggestion.

This is the Python scriptlet I wrote to edit the file's metadata from the filename:
```
#pip3 install ebookmeta
import ebookmeta
import pyperclip
import os, sys

#======== grab input filename from clipboard
INPUTFILE = pyperclip.paste()
if not INPUTFILE or ".epub" not in INPUTFILE:
	print ("Must pass an EPUB filename")
	exit()

print(f"Handling {INPUTFILE}")

#======== grab author + title from filename: author#title.epub
x = [x.strip() for x in INPUTFILE.split('#')]
file_author=x[0]
#ignore file extension
file_title, _ = os.path.splitext(x[1])

#======== edit metadata: set author + title
meta = ebookmeta.get_metadata(INPUTFILE)
meta.set_author_list_from_string(file_author)
meta.title = file_title
print(f"Title:{meta.title}, Author:{meta.author_list[0]}")
ebookmeta.set_metadata(INPUTFILE, meta)
```

**Comment by Shohreh** [comment]
I checked the HTML source of one of those pages: The extension _does_ grab what's in the title section in the header ("Generic title"), and it contains no author infos, so there's probably no reliable better way to do it. The script is good enough for my need. Thank you.

**Comment by erikbrinkman** [comment]
If you don't mind, I'd like to actually set title however ebookmeta is setting it, so you don't have to run the script. Which is why I want to keep this open
