### ISSUE TITLE
Conversion to epub failed

### ISSUE THREAD

**Issue by mseliger** [hafaio/repub#3]
because of the filename

Page: 
https://www.nzz.ch/wissenschaft/ki-fuehren-uns-algorithmen-ins-posttheoretische-zeitalter-ld.1733932
PageTitle: 
KI: Führen uns Algorithmen ins posttheoretische Zeitalter?

Is it possible to edit the filename?

Greetings, Maria

**Comment by erikbrinkman** [comment]
If I understand what's happening. You're trying to save it as a file, but it's erroring out because the filename is invalid (likely due to the unicode of the umlaut)?

I haven't spent much time on this flow, so I'm curious if you have thoughts. I'm about to submit a change that will make the filename:
`KI_ F_C3_BChren uns Algorithmen ins posttheoretische Zeitalter_`
which is safe and wont error, but is also pretty hard to read.

In order to address your real issue, I also added a section to the options to allow prompting for a filename, which works as you would expect:

![Screenshot 2023-04-30 115501](https://user-images.githubusercontent.com/858926/235365913-c9f128a7-d532-4898-837c-a2291a970faa.png)

These changes should be out in v2.1.0, which should be up in a day or two.

However, since I have you, I was wondering if you could give feedback on how well this works, or if there's something better? Right now I'm making it safe by just treating it as a url, but it makes the names pretty unreadable. Would it be better to try and make it safe by converting to just a "u" without the umlaut? Is there a better way to prompt for a filename?

Thanks for the feedback!

**Comment by mseliger** [comment]
Hello Erik,

thank you for the new version. Now I can save the page and there is no error more.
