### ISSUE TITLE
<figure> or <iframe> is being excluded from epub document

### ISSUE THREAD

**Issue by brianblank** [hafaio/repub#5]
Either the `<figure>` or more likely the `<iframe>` block is being  excluded from the document.
![bug2-1](https://github.com/hafaio/repub/assets/6259947/dc036087-f51a-467c-bdb3-081325dff6be)
![bug2-3](https://github.com/hafaio/repub/assets/6259947/c0307f97-7914-43e5-a118-a31436cd12dc)
![bug2-2](https://github.com/hafaio/repub/assets/6259947/251063c2-7f86-4da9-8e4f-d9faa3cbb0db)

**Comment by erikbrinkman** [comment]
It's almost certainly the iframe. Unlike `<pre>` where I knew the issue was easily addressable, this might be a little more challenging. As a result, I can't really make guarantees on how long it takes to fix. Also, It'd help if you could send a public page that exhibits the same problem. It' pretty difficult to debug from screenshots.

I have a few initial thoughts which could all be playing a roll.
1. the summarizer "readability" that I use might inherently treat iframes as ads, not sure if there'd be an easy way to fix this
2. like images, since the iframes render external content, I need to appropriately save and render the iframe content. This is likely possible, but might be difficult
3. epub frormat may not really support iframes, so I'll need to do something like, extracting the content and inserting into the parent. This might not end up working well, but also should be feasible.

It could be any combination of these, and each of the fixes is a little in depth, so if you could send a reference that would help!

**Comment by brianblank** [comment]
Thanks again for the fast reply.  Here are the URLs you asked for related to the problem above:

- Article: https://medium.com/truefieng/formal-verification-for-n00bs-part-1-b4781db2a383
- iFrame URL: https://medium.com/media/7ce81e30fb95cd3cd3e445fb337f8282

**Comment by brianblank** [comment]
Just a thought that may make it easier to resolve this (hopefully)... I would guess that your reader is using the DOM that is already loaded in memory and is therefore not going to the Internet to re-fetch the material that is already in the DOM of the browser (maybe I'm wrong).  If this is the case, would it be possible to simply transpose or treat the `<iframe>` as a `<div>` instead rather than treating this as a separate document?

Also, with regard to your comment about treating iframes as advertisements, I think this makes a lot of sense.  One option is that in this case, the iframe is on the same website as the main article.  Could be used as a differentiator between an extension of the article vs an advertisement?  Also, maybe include an option to allow iframe to be or not to be treated as an article vs advertisement.  Last recommendation is to collect the iframe.class details in the options to be treated as an article instead of the default advertisement?

**Comment by erikbrinkman** [comment]
Unfortunately, even though the chrome dev tools show it as one DOM, internally it's actually not rendered that way, so this doesn't really work. Additionally, in order to require fewer permissions, I use the page_capture api, which is the same as saying "save page as... > single file". In this context, every distinct url is encoded separately. Finally, iframes have their own semantics, both a separate window that has it's own bounds, and potentially separate styles (as it's a whole document). This means I could potentially get something hacky by just including it, and that might actually work better for the summarizer, but it's not immediately clear that that's the best path. I really just need to see what's happening where and try to figure out what works best.

Thanks for the links!

**Comment by erikbrinkman** [comment]
Looking into this a little further, the iframes are being filtered out by the summarizer readability, but that is possible to prevent. However, that might not be a good default as a lot of inline ads are in iframes, so whether that's toggled on by default might require some more investigation.

However, there's a larger problem and that's that pageCapture isn't including the content of iframe. I'm not really sure why this is happening. I submitted a [bug in chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1489346), however the last bug I submitted with respect to the pageCapture API was over two years ago and there's no progress. That one I was able to partially work around, this one, not so much.

That means I really see two possible paths forward:
1. wait until it's fixed in chromium, who knows how long this will take
2. get the page source some other way

For 2., I used to use this approach before there are several major problems with it.
* It requires more permissions, e.g. I'll likely need to run arbitrary javascript on the target page, which is a little more suss. I don't think anyone who uses this really cares, but I still dislike the idea of needing more permissions than necessary.
* It adds significantly more complexity as the whole script needs to be rewritten to use the resources as they exist, versus relying on the browser to serialize everything necessary (which it's not really doing). This will be an almost entire rewrite of the library.

All this is to say, that while I acknowledge that this is a current limitation, I don't know if I have the will to devote time to fixing it. PRs are welcome, and I'm happy to give guidance on how I think the best way to achieve it is, but I'm not going to actively plan to address this :/

**Comment by erikbrinkman** [comment]
An update from the issue. Apparently chrome is lazy, so if you never observe the iframe, it never loads, and won't get included in the mhtml. Knowing this, I can get an mhtml that has the iframe and work from there. I'm also going to see if there's a way to force chrome to load everything.

**Comment by brianblank** [comment]
Thank you!

**Comment by erikbrinkman** [comment]
I've published the fix in version 3.2. A few general notes:

* like with some images this won't capture resources that were never loaded. In the example document, if you don't scroll down, the iframe never loads, never gets picked up in the output, and never rendered. I don't know what a long term fix for this is, because I'm not sure what the ultimate cause is, e.g. if it's chrome being lazy with loading, or the page itself not loading the iframe until it's in the viewport. The former should be fixable, the later is going to require loading the javascript and intentionally "scrolling" down before capturing, which is probably infeasible.
* it's gated behind a setting "Remove IFrames" in "EPub Options", so make sure to uncheck that. I default it to false so as not to break the way things are currently rendering.
* The results are... okay at best. In the example you linked, the code is inserted as normal paragraphs, I think because the render itself does everything in css, and part of the point of summarizing is to strip most of the unnecessary css.

As a result of the last point, this might not meet your needs quite yet, or at least, it should render it, but not in an ideal format. Since it's gated off by default, I'm open to other changes to how this works. However, I'm going to ask you to guide the direction, because I'm really not sure how to best preserve the content of the iframe with appropriate styles. For this specific example it seems best to just encode it in a pre, but that's probably not a generic solution.

Anyway, if you have further thoughts, feel free to reopen!
