### ISSUE TITLE
<a href> + <span> causing page breaks + black pages

### ISSUE THREAD

**Issue by brianblank** [hafaio/repub#7]
An article that I'm trying to convert to ePub using your tool is adding a significant amount of page breaks and black pages, increasing the size of the document from 11 pages (as per the PDF converter utility that I'm using) to over 129 pages using this utility.

The URL for reference is this: https://ethereum.org/en/developers/docs/smart-contracts/formal-verification/

Here are the screen prints:
![bug3-1](https://github.com/hafaio/repub/assets/6259947/5569eb68-f236-46a6-9f1b-a3123b273142)
![bug3-2](https://github.com/hafaio/repub/assets/6259947/780c37a2-e8e7-419b-b4ff-86606280cdd6)
![bug3-3](https://github.com/hafaio/repub/assets/6259947/1faa4f9f-2198-4a5e-93af-d75204a5fa4f)

**Comment by erikbrinkman** [comment]
Initially, I'm not sure page count is the right way to view it, as font size etc plays into it. That being said, 11 -> 129 says something bad is happening.

I have noticed this happening occasionally, but I didn't know what was causing it, and it was never annoying enough to try and fix.

Glancing at the specific part you referenced, it seems like after the link there's an icon. The summarizer isn't stripping this, so it gets read as an image. It's an svg image, so has no size, and therefore I render it the size of a page. Since it's inside the link attribute it's getting rendered inline, causing both the large page breaks and the odd full width justification.

One thing I wanted to do was just check if an image is all black or white, and if so, strip it. That might be enough to get this to work as necessary.

**Comment by erikbrinkman** [comment]
After looking into this there were two somewhat insidious issues.

1. the package I wrote to create epubs sanitized the xhtml (because I copied another library). Almost no svg properties were preserved, so I had to tweak the library to no longer sanitize svgs.
2. after fixing 1, it turned out that despite that, remarkable doesn't render inline svgs properly. Therefore I had to find inline svgs, replace them with an `<img/>` element, and save an extra image to the epub. This might cause some other problems, but since we don't keep the original css, it seems unlikely. The example page now renders properly (about 21 pages).

Unfortunately, the "(opens in a new tab)" is still visible because css is meant to hide it. I don't offhand know how to best handle cases like this. Potentially I could check if an element would be hidden under the normal css, and if so remove it from the epub, but this sounds complicated and error prone. If it's really annoying, please file a separate issue.

Still, the solution to 2, worked, and 3.1 is up, so updating to that should fix pages like this.
